install:
  - rm -rf src/public || exit 0

script:
  - cd src
  - ../bin/hugo

branches:
  only:
  - gh-pages

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: src/public
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages
