install:
  - rm -rf public || exit 0

script:
  - cd src
  - ../bin/hugo

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  target_branch: master
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: gh-pages